# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-demo-j',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/nbdev-demo-j',
                'lib_path': 'nbdev_demo_j'},
  'syms': { 'nbdev_demo_j.card': { 'nbdev_demo_j.card.Card': ('card.html#card', 'nbdev_demo_j/card.py'),
                                   'nbdev_demo_j.card.Card.__eq__': ('card.html#card.__eq__', 'nbdev_demo_j/card.py'),
                                   'nbdev_demo_j.card.Card.__gt__': ('card.html#__gt__', 'nbdev_demo_j/card.py'),
                                   'nbdev_demo_j.card.Card.__init__': ('card.html#__init__', 'nbdev_demo_j/card.py'),
                                   'nbdev_demo_j.card.Card.__lt__': ('card.html#__lt__', 'nbdev_demo_j/card.py'),
                                   'nbdev_demo_j.card.Card.__str__': ('card.html#__str__', 'nbdev_demo_j/card.py'),
                                   'nbdev_demo_j.card.Card.j': ('card.html#j', 'nbdev_demo_j/card.py')},
            'nbdev_demo_j.core': {'nbdev_demo_j.core.foo': ('core.html#foo', 'nbdev_demo_j/core.py')}}}